# Generated by Django 3.2.9 on 2021-11-21 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wrtapp', '0002_auto_20211120_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
