# Generated by Django 3.2.9 on 2021-11-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrtapp', '0003_statistics_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
